### ISSUE TITLE
Clicking and loading more comments on page

### ISSUE THREAD

**Issue by NgGeorge** [NgGeorge/Waterfall#6]

**Comment by k-chung** [comment]
Needs to wait for autoscroll to reach the bottom, then look for the :last instance of "morechildren" div in the thread page (if it exists)

**Comment by NgGeorge** [comment]
I had to do it differently, because the last instance of morechildren isn't necessarily the right thing we're looking for. The last element will always be a 'thing' div but the last 'morechildren' isn't necessarily the last 'thing' div on the page. So in that scenario it would be finding the wrong button to click.

**Comment by NgGeorge** [comment]
PR here : https://github.com/NgGeorge/Waterfall/pull/13
